name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build app
      run: lein with-profile +prod uberjar

    - name: Copy artifacts
      run: |
        mkdir -p deploy
        mv target/aural-training-server.jar .
        mv docker/Dockerfile .
        mv docker/docker-compose.yml .

    - name: Deploy to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_IP }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
        source: "aural-training-server.jar,docker-compose.yml,Dockerfile"
        target: "aural-training-deploy"

    # - name: Start app with docker-compose
    #   run: |
    #     ssh ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_IP }} 'cd /path/to/deployment && docker-compose up -d'
