name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Typescript
      run: |
        npm install
        npm run compile

    - name: Build Clojure server
      run: lein with-profile +prod uberjar

    - name: Copy artifacts
      run: |
        mkdir -p deploy
        mv target/aural-training-server.jar .
        mv docker/Dockerfile .
        mv docker/docker-compose.yml .

    - name: Transfer to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_IP }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
        source: "aural-training-server.jar,docker-compose.yml,Dockerfile,resources,scripts/run-server-jar.template"
        target: "aural-training-deploy"

    - name: restart service
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.DIGITALOCEAN_IP }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
        script: |
          cd aural-training-deploy
          cp scripts/run-server-jar.template scripts/run-server-jar
          docker-compose up --build -d
